version: '3'

services:
  front-end:
    image: zzzrq/dropbox-hackathon-frontend:v1
    ports:
      - '3001:3001'
    depends_on: 
      - node-app
    networks: 
      - node-network
    environment:
      - REACT_APP_BACKEND_URL=http://18.218.149.183:3000

  node-app:
    # build: .
    # image: node-app
    # tty: true
    image: zzzrq/dropbox-hackathon-backend:v1
    # environment:
    #   - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    environment:
      - MONGODB_URL=mongodb+srv://zrq2839:testtest0283@petitiondb.dcp6cid.mongodb.net/?retryWrites=true&w=majority
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
